// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbw2dKxGxopSCWq3isGEDVXRyk5linVeA',
    appId: '1:1076822423591:web:3c53438faf37174778b602',
    messagingSenderId: '1076822423591',
    projectId: 'short-term-hospital-stay',
    authDomain: 'short-term-hospital-stay.firebaseapp.com',
    storageBucket: 'short-term-hospital-stay.appspot.com',
    measurementId: 'G-Z1RMCS68EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASVh08xDl7eZEW8psy01Y7ZVNPk2WjBM',
    appId: '1:1076822423591:android:99a8c70a6346e8cf78b602',
    messagingSenderId: '1076822423591',
    projectId: 'short-term-hospital-stay',
    storageBucket: 'short-term-hospital-stay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNM7e97Ye8balzEdXPUiw1MnqItxSnq_Y',
    appId: '1:1076822423591:ios:80008853984d593778b602',
    messagingSenderId: '1076822423591',
    projectId: 'short-term-hospital-stay',
    storageBucket: 'short-term-hospital-stay.appspot.com',
    iosBundleId: 'com.example.shortTermHospitalStay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNM7e97Ye8balzEdXPUiw1MnqItxSnq_Y',
    appId: '1:1076822423591:ios:f3e965c71266425578b602',
    messagingSenderId: '1076822423591',
    projectId: 'short-term-hospital-stay',
    storageBucket: 'short-term-hospital-stay.appspot.com',
    iosBundleId: 'com.example.shortTermHospitalStay.RunnerTests',
  );
}
